### ISSUE TITLE
[B] Error while installing

### ISSUE THREAD

**Issue by schroef** [redmunds/brackets-quick-markup#49]
rv 3.3.0
os 10.11.6
Brackets 1.13

I get an error when im installing, something about restart error. See screengrab, not sure you need more info

<img width="622" alt="screen shot 2018-08-16 at 16 39 22" src="https://user-images.githubusercontent.com/6923008/44233891-1c207400-a173-11e8-874f-1f65b2acdf03.png">

PS i noticed this in the Inspector

`Failed to load resource: net::ERR_FILE_NOT_FOUND
/utils/DeprecationWarning.js:88 Deprecated: Do not use $().on/off() on Brackets modules and model objects. Call on()/off() directly on the object without a $() wrapper.
    at new jQuery.fn.init (/brackets.js:467:36)
    at n (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:19:405)
    at handleActiveEditorChange (file:///Users/romboutversluijs/Library/Application%20Support/Brackets/extensions/user/pflynn.charcount/main.js:57:13)
    at Object.trigger (/utils/EventDispatcher.js:229:40)
    at _notifyActiveEditorChanged (/editor/EditorManager.js:161:17)
    at _handleCurrentFileChange (/editor/EditorManager.js:178:9)
    at Object.trigger (/utils/EventDispatcher.js:229:40)
    at eval (/view/MainViewManager.js:1118:29)
    at Pane.trigger (/utils/EventDispatcher.js:229:40)`

**Comment by schroef** [comment]
Hmmm th pflynn is something else i guess, its not related. Ill check if i can do something im not into this code though.
